export interface NicheData {
  slug: string;
  name: string;
  nameSingular: string;
  headline: string;
  subheadline: string;
  painPoints: string[];
  features: { title: string; desc: string }[];
  demoName: string;
  demoCity: string;
  demoUrl: string;
  demoGradient: string;
  demoCardBg: string;
  demoCardTextColor: string;
  demoIsDark: boolean;
  seoTitle: string;
  seoDescription: string;
  rolePreset: string;
  agencyComparison: string;
  hubDesc: string;
  relatedSlugs: string[];
}

const ALL_SLUGS = [
  "dentists",
  "barbershops",
  "tattoo-shops",
  "restaurants",
  "auto-shops",
  "coffee-shops",
  "med-spas",
  "fitness-studios",
  "plumbers",
  "real-estate-agents",
];

function relatedFor(slug: string): string[] {
  return ALL_SLUGS.filter((s) => s !== slug).slice(0, 5);
}

export const niches: NicheData[] = [
  {
    slug: "dentists",
    name: "Dentists",
    nameSingular: "Dentist",
    headline: "Websites for Dentists in Sacramento",
    subheadline: "Custom designed. SEO optimized to bring new patients to your practice. Live in 14 days. No upfront cost.",
    painPoints: [
      "Patients Google 'dentist near me' and your outdated site loses them in 3 seconds.",
      "Your competitor down the street has a modern site with online booking. You don't.",
      "You're paying a dental marketing agency $300–500/month for a cookie-cutter template.",
    ],
    features: [
      { title: "Custom Design", desc: "Built to reflect your practice, not a template every dentist uses." },
      { title: "Patient-Focused SEO", desc: "Rank for 'dentist in Rocklin CA' and your specific services." },
      { title: "Mobile Optimized", desc: "Patients are searching on their phones. Your site will look perfect." },
      { title: "Online Forms", desc: "New patient forms, appointment requests, contact forms built in." },
      { title: "Self-Service Edits", desc: "Update hours, add a new doctor, change services yourself." },
      { title: "HIPAA Aware Design", desc: "Built with healthcare best practices in mind." },
    ],
    demoName: "Heritage Oak Dental",
    demoCity: "Folsom, CA",
    demoUrl: "heritageoakdental.com",
    demoGradient: "from-sky-50 via-blue-50 to-indigo-50",
    demoCardBg: "#f0f8ff",
    demoCardTextColor: "#1a2a4a",
    demoIsDark: false,
    seoTitle: "Dentist Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for dental practices in Sacramento, Rocklin, Roseville and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "dentist",
    agencyComparison: "Dental marketing agencies charging $300–500/month for template sites",
    hubDesc: "Custom websites that bring new patients to your practice.",
    relatedSlugs: relatedFor("dentists"),
  },
  {
    slug: "barbershops",
    name: "Barbershops",
    nameSingular: "Barbershop",
    headline: "Websites for Barbershops in Sacramento",
    subheadline: "Custom designed. SEO optimized to keep your chairs full. Live in 14 days. No upfront cost.",
    painPoints: [
      "Clients search for barbers on their phone. If your site isn't mobile-perfect, they scroll past.",
      "You're relying on Instagram alone. But Instagram doesn't rank on Google.",
      "Walk-ins are declining. Your online presence should be filling your chairs.",
    ],
    features: [
      { title: "Custom Design", desc: "Your site should feel like your shop. We build it to match your vibe." },
      { title: "Local SEO", desc: "Rank for 'barbershop near me' in your neighborhood." },
      { title: "Mobile First", desc: "Clients find you on their phone. Your site will look clean." },
      { title: "Gallery", desc: "Show off your cuts. A real portfolio, not just an Instagram embed." },
      { title: "Self-Service Edits", desc: "Update prices, hours, and photos yourself." },
      { title: "Fast Launch", desc: "Live in 14 days. Start booking this month." },
    ],
    demoName: "Kings Cuts",
    demoCity: "Sacramento, CA",
    demoUrl: "kingscuts.com",
    demoGradient: "from-stone-900 via-neutral-900 to-zinc-900",
    demoCardBg: "#1a1a1a",
    demoCardTextColor: "#e5e5e5",
    demoIsDark: true,
    seoTitle: "Barbershop Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for barbershops in Sacramento, Roseville, Rocklin and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "salon owner",
    agencyComparison: "Traditional agencies charging $3,000–8,000 upfront",
    hubDesc: "Modern sites that keep your chairs full and show off your work.",
    relatedSlugs: relatedFor("barbershops"),
  },
  {
    slug: "tattoo-shops",
    name: "Tattoo Shops",
    nameSingular: "Tattoo Shop",
    headline: "Websites for Tattoo Shops in Sacramento",
    subheadline: "Custom designed. SEO optimized to fill your booking calendar. Live in 14 days. No upfront cost.",
    painPoints: [
      "Your portfolio deserves better than an Instagram grid. A real site shows your art properly.",
      "Clients want to browse your work, check your availability, and book — all in one place.",
      "You're losing bookings to shops with better websites, not better artists.",
    ],
    features: [
      { title: "Custom Design", desc: "Your site should showcase your style, not look like every other shop." },
      { title: "Portfolio Gallery", desc: "Display your work in a way Instagram can't. Large, beautiful, browseable." },
      { title: "Booking Integration", desc: "Clients can request appointments directly from your site." },
      { title: "Local SEO", desc: "Rank for 'tattoo shop in Sacramento' and your specific specialties." },
      { title: "Mobile Optimized", desc: "Clients browse your portfolio on their phone. Make it count." },
      { title: "Fast Launch", desc: "Live in 14 days. Start taking online bookings this month." },
    ],
    demoName: "Black Tide Tattoo",
    demoCity: "Sacramento, CA",
    demoUrl: "blacktidetattoo.com",
    demoGradient: "from-zinc-900 via-black to-neutral-900",
    demoCardBg: "#09090b",
    demoCardTextColor: "#e4e4e7",
    demoIsDark: true,
    seoTitle: "Tattoo Shop Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for tattoo shops in Sacramento, Folsom, Davis and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "business owner",
    agencyComparison: "Traditional agencies charging $3,000–8,000 upfront",
    hubDesc: "Portfolio-driven sites that fill your booking calendar.",
    relatedSlugs: relatedFor("tattoo-shops"),
  },
  {
    slug: "restaurants",
    name: "Restaurants",
    nameSingular: "Restaurant",
    headline: "Websites for Restaurants in Sacramento",
    subheadline: "Custom designed. SEO optimized to fill your tables. Live in 14 days. No upfront cost.",
    painPoints: [
      "Customers check your menu online before they ever walk in the door.",
      "If your site is slow, ugly, or missing your hours — they're going to the place next door.",
      "You're paying DoorDash and Yelp to own your customer relationships.",
    ],
    features: [
      { title: "Custom Design", desc: "Your site should feel as good as your food tastes." },
      { title: "Digital Menu", desc: "Beautiful, up-to-date menu your customers can browse before they arrive." },
      { title: "Local SEO", desc: "Rank for 'restaurants in Sacramento' and your cuisine type." },
      { title: "Mobile Optimized", desc: "Customers check menus on their phone. Yours will look perfect." },
      { title: "Hours & Location", desc: "Always accurate hours, directions, and contact info front and center." },
      { title: "Fast Launch", desc: "Live in 14 days. Start driving traffic before your next weekend rush." },
    ],
    demoName: "Maison Caldo",
    demoCity: "Sacramento, CA",
    demoUrl: "maisoncaldo.com",
    demoGradient: "from-neutral-900 via-neutral-800 to-zinc-900",
    demoCardBg: "#1a1a1a",
    demoCardTextColor: "#ffffff",
    demoIsDark: true,
    seoTitle: "Restaurant Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for restaurants in Sacramento, Elk Grove, Davis and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "restaurant owner",
    agencyComparison: "Traditional agencies charging $4,000–10,000 upfront",
    hubDesc: "Appetizing sites that fill your tables and cut Yelp dependence.",
    relatedSlugs: relatedFor("restaurants"),
  },
  {
    slug: "auto-shops",
    name: "Auto Shops",
    nameSingular: "Auto Shop",
    headline: "Websites for Auto Shops in Sacramento",
    subheadline: "Custom designed. SEO optimized to bring in more repair jobs. Live in 14 days. No upfront cost.",
    painPoints: [
      "When someone's car breaks down, they Google 'auto shop near me.' Your site needs to be there.",
      "Your competitors have online appointment booking. You're still answering every call manually.",
      "A professional website builds trust before the customer ever walks through your bay door.",
    ],
    features: [
      { title: "Custom Design", desc: "Professional site that builds trust before customers walk in your door." },
      { title: "Local SEO", desc: "Rank for 'auto shop near me' and your specific services." },
      { title: "Online Scheduling", desc: "Let customers book appointments online. Fewer phone interruptions." },
      { title: "Service Menu", desc: "List all your services so customers know exactly what you offer." },
      { title: "Mobile Optimized", desc: "People Google repairs from their car. Your site needs to work perfectly." },
      { title: "Fast Launch", desc: "Live in 14 days. More bookings by end of the month." },
    ],
    demoName: "Sunrise Auto",
    demoCity: "Rancho Cordova, CA",
    demoUrl: "sunriseautoca.com",
    demoGradient: "from-slate-200 via-zinc-100 to-gray-100",
    demoCardBg: "#f4f4f5",
    demoCardTextColor: "#18181b",
    demoIsDark: false,
    seoTitle: "Auto Shop Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for auto shops in Sacramento, Rancho Cordova, Citrus Heights and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "contractor",
    agencyComparison: "Traditional agencies charging $3,000–8,000 upfront",
    hubDesc: "Trust-building sites that bring in repair jobs around the clock.",
    relatedSlugs: relatedFor("auto-shops"),
  },
  {
    slug: "coffee-shops",
    name: "Coffee Shops",
    nameSingular: "Coffee Shop",
    headline: "Websites for Coffee Shops in Sacramento",
    subheadline: "Custom designed. SEO optimized to turn visitors into regulars. Live in 14 days. No upfront cost.",
    painPoints: [
      "People Google 'coffee near me' before they walk anywhere. Your site is your storefront.",
      "Your vibe is everything. Your website should feel like your shop.",
      "A great site turns a one-time visitor into a regular.",
    ],
    features: [
      { title: "Custom Design", desc: "Your website should feel like your shop — warm, inviting, distinctly yours." },
      { title: "Local SEO", desc: "Rank for 'coffee near me' and get found by people in your neighborhood." },
      { title: "Digital Menu", desc: "Display your drinks and food in a beautiful, scannable format." },
      { title: "Mobile First", desc: "People find coffee shops on their phone. Yours will look great." },
      { title: "Hours & Location", desc: "Make it dead simple to find you, check your hours, and get directions." },
      { title: "Fast Launch", desc: "Live in 14 days. Start building your regular customer base online." },
    ],
    demoName: "Valley Roots Cafe",
    demoCity: "Davis, CA",
    demoUrl: "valleyrootscafe.com",
    demoGradient: "from-amber-100 via-orange-50 to-yellow-50",
    demoCardBg: "#f5ede0",
    demoCardTextColor: "#1a3c2a",
    demoIsDark: false,
    seoTitle: "Coffee Shop Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for coffee shops in Sacramento, Davis, Folsom and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "business owner",
    agencyComparison: "Traditional agencies charging $3,000–8,000 upfront",
    hubDesc: "Cozy, on-brand sites that make people want to visit your shop.",
    relatedSlugs: relatedFor("coffee-shops"),
  },
  {
    slug: "med-spas",
    name: "Med Spas",
    nameSingular: "Med Spa",
    headline: "Websites for Med Spas in Sacramento",
    subheadline: "Custom designed. SEO optimized to convert research into bookings. Live in 14 days. No upfront cost.",
    painPoints: [
      "Clients research treatments online for weeks before booking. Your site is your first consultation.",
      "You're competing against med spas with $10,000 agency websites. You don't need to spend that.",
      "Online booking and service menus aren't optional anymore — they're expected.",
    ],
    features: [
      { title: "Custom Design", desc: "Luxury design that matches the experience you deliver in your spa." },
      { title: "Service Menu", desc: "Detailed service and treatment pages that educate and convert." },
      { title: "Online Booking", desc: "Let clients book consultations and appointments directly from your site." },
      { title: "Local SEO", desc: "Rank for 'med spa Sacramento' and your specific treatments." },
      { title: "Before & After Gallery", desc: "Showcase your results in a professional, compelling way." },
      { title: "Mobile Optimized", desc: "Clients research treatments on their phone for weeks before booking." },
    ],
    demoName: "Lotus Med Spa",
    demoCity: "Granite Bay, CA",
    demoUrl: "lotusmedspa.com",
    demoGradient: "from-rose-50 via-pink-50 to-fuchsia-50",
    demoCardBg: "#fdf2f8",
    demoCardTextColor: "#831843",
    demoIsDark: false,
    seoTitle: "Med Spa Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for med spas in Sacramento, Granite Bay, Roseville and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "salon owner",
    agencyComparison: "Med spa marketing agencies charging $5,000–10,000 for luxury template sites",
    hubDesc: "Luxury sites that convert research into bookings for your spa.",
    relatedSlugs: relatedFor("med-spas"),
  },
  {
    slug: "fitness-studios",
    name: "Fitness Studios",
    nameSingular: "Fitness Studio",
    headline: "Websites for Fitness Studios in Sacramento",
    subheadline: "Custom designed. SEO optimized to convert browsers into members. Live in 14 days. No upfront cost.",
    painPoints: [
      "Members want to see your schedule, pricing, and vibe before they try a class.",
      "Your competitor has a slick site with online class booking. You have a Facebook page.",
      "A professional website converts curious browsers into paying members.",
    ],
    features: [
      { title: "Custom Design", desc: "Energy and professionalism that matches what happens inside your studio." },
      { title: "Class Schedule", desc: "Always up-to-date schedule so members know exactly when to show up." },
      { title: "Online Membership", desc: "Let new members sign up and existing members manage online." },
      { title: "Local SEO", desc: "Rank for 'fitness studio Sacramento' and your specific classes." },
      { title: "Mobile Optimized", desc: "Members check schedules on their phone. Yours will be perfect." },
      { title: "Fast Launch", desc: "Live in 14 days. Convert curious browsers into paying members." },
    ],
    demoName: "Forge Fitness",
    demoCity: "Roseville, CA",
    demoUrl: "forgefitness.com",
    demoGradient: "from-neutral-900 via-zinc-900 to-stone-900",
    demoCardBg: "#171717",
    demoCardTextColor: "#e5e5e5",
    demoIsDark: true,
    seoTitle: "Fitness Studio Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for fitness studios in Sacramento, Roseville, Rocklin and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "business owner",
    agencyComparison: "Traditional agencies charging $3,000–8,000 upfront",
    hubDesc: "High-energy sites that convert visitors into gym members.",
    relatedSlugs: relatedFor("fitness-studios"),
  },
  {
    slug: "plumbers",
    name: "Plumbers",
    nameSingular: "Plumber",
    headline: "Websites for Plumbers in Sacramento",
    subheadline: "Custom designed. SEO optimized so emergency calls go to you. Live in 14 days. No upfront cost.",
    painPoints: [
      "Emergency calls go to whoever shows up first on Google. That should be you.",
      "Homeowners judge your professionalism by your website before they call.",
      "Every day without a real site is money going to your competitors.",
    ],
    features: [
      { title: "Custom Design", desc: "Professional site that makes homeowners trust you before you arrive." },
      { title: "Local SEO", desc: "Show up first when someone Googles 'plumber near me' in an emergency." },
      { title: "Online Quotes", desc: "Let customers request quotes and service calls from your site." },
      { title: "Service Area", desc: "Clearly show your service areas across Sacramento, Roseville, and beyond." },
      { title: "Mobile Optimized", desc: "People Google plumbers from their phone in a crisis. Be ready." },
      { title: "Fast Launch", desc: "Live in 14 days. Be on Google before your next competitor sets up shop." },
    ],
    demoName: "Sunrise Plumbing",
    demoCity: "Sacramento, CA",
    demoUrl: "sunriseplumbing.com",
    demoGradient: "from-blue-100 via-sky-100 to-cyan-50",
    demoCardBg: "#e0f2fe",
    demoCardTextColor: "#0c4a6e",
    demoIsDark: false,
    seoTitle: "Plumber Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for plumbers in Sacramento, Lincoln, Elk Grove and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "contractor",
    agencyComparison: "Traditional agencies charging $3,000–8,000 upfront",
    hubDesc: "Emergency-ready sites that put you first on Google when it counts.",
    relatedSlugs: relatedFor("plumbers"),
  },
  {
    slug: "real-estate-agents",
    name: "Real Estate Agents",
    nameSingular: "Real Estate Agent",
    headline: "Websites for Real Estate Agents in Sacramento",
    subheadline: "Custom designed. SEO optimized to position you as the agent in your market. Live in 14 days. No upfront cost.",
    painPoints: [
      "Your brokerage template site looks like every other agent in town.",
      "Clients want to see YOUR brand, YOUR listings, YOUR story — not a generic portal.",
      "A custom site positions you as the agent, not just an agent.",
    ],
    features: [
      { title: "Custom Design", desc: "A site that's distinctly yours — not your brokerage's generic template." },
      { title: "Listings Integration", desc: "Showcase your active and sold listings in a beautiful, searchable format." },
      { title: "Local SEO", desc: "Rank for your name, your neighborhoods, and 'real estate agent Sacramento'." },
      { title: "Lead Capture", desc: "Contact forms, buyer/seller guides, and CTA at every scroll point." },
      { title: "Mobile Optimized", desc: "Clients browse listings on their phone at open houses. Look sharp." },
      { title: "Bio & Reviews", desc: "Your story, your approach, and your testimonials front and center." },
    ],
    demoName: "Hawkins Properties",
    demoCity: "Sacramento, CA",
    demoUrl: "hawkinsproperties.com",
    demoGradient: "from-emerald-50 via-teal-50 to-green-50",
    demoCardBg: "#f0fdf4",
    demoCardTextColor: "#14532d",
    demoIsDark: false,
    seoTitle: "Real Estate Agent Website Design Sacramento | GreyWhale",
    seoDescription: "Custom websites for real estate agents in Sacramento, Folsom, Granite Bay and surrounding areas. No upfront cost. SEO optimized. Live in 14 days. Starting at $149/month.",
    rolePreset: "realtor",
    agencyComparison: "Traditional agencies charging $4,000–10,000 upfront for agent sites",
    hubDesc: "Personal brand sites that set you apart from every other agent.",
    relatedSlugs: relatedFor("real-estate-agents"),
  },
];

export function getNicheBySlug(slug: string): NicheData | undefined {
  return niches.find((n) => n.slug === slug);
}

export const nicheNames: Record<string, string> = {
  "dentists": "Dentists",
  "barbershops": "Barbershops",
  "tattoo-shops": "Tattoo Shops",
  "restaurants": "Restaurants",
  "auto-shops": "Auto Shops",
  "coffee-shops": "Coffee Shops",
  "med-spas": "Med Spas",
  "fitness-studios": "Fitness Studios",
  "plumbers": "Plumbers",
  "real-estate-agents": "Real Estate Agents",
};
